server:
  sslCertificatePath: /tmp/sslcert/server.crt
  sslPrivateKeyPath: /tmp/sslcert/server.pem
backplane:
  redisUri: "redis://localhost:6379"
  queues:
    - name: "cpu"
      properties:
        - name: "min-cores"
          value: "*"
        - name: "max-cores"
          value: "*"
worker:
  publicName: "localhost:8981"
