server:
  metrics:
    publisher: LOG
    logLevel: FINEST
    topic: test
    topicMaxConnections: 1000
    secretName: test
backplane:
  redisUri: "redis://localhost:6379"
  queues:
    - name: "cpu"
      properties:
        - name: "min-cores"
          value: "*"
        - name: "max-cores"
          value: "*"
worker:
  publicName: "localhost:8981"
