digestFunction: SHA256
server:
  instanceType: SHARD
  name: shard
  actionCachePolicy: READ_AND_WRITE
  port: 8980
  prometheusPort: 9090
  grpcMetrics:
    enabled: false
    provideLatencyHistograms: false
  casWriteTimeout: 3600
  bytestreamTimeout: 3600
  sslCertificatePath:
  runDispatchedMonitor: true
  dispatchedMonitorIntervalSeconds: 1
  runOperationQueuer: true
  ensureOutputsPresent: false
  maxEntrySizeBytes: 2147483648 # 2 * 1024 * 1024 * 1024
  maxRequeueAttempts: 5
  useDenyList: true
  grpcTimeout: 3600
  maximumActionTimeout: 3600
  executeKeepaliveAfterSeconds: 60
  recordBesEvents: false
  admin:
    deploymentEnvironment: aws
    clusterId: local
    clusterEndpoint: "grpc://localhost"
    region: us-east-1
  metrics:
    logLevel: INFO
backplane:
  type: SHARD
  redisUri: "redis://localhost:6379"
  redisPassword:
  redisNodes:
  jedisPoolMaxTotal: 4000
  workersHashName: "Workers"
  workerChannel: "WorkerChannel"
  actionCachePrefix: "ActionCache"
  actionCacheExpire: 2419200 # 4 weeks
  actionBlacklistPrefix: "ActionBlacklist"
  actionBlacklistExpire: 3600 # 1 hour
  invocationBlacklistPrefix: "InvocationBlacklist"
  operationPrefix: "Operation"
  operationExpire: 604800 # 1 week
  preQueuedOperationsListName: "{Arrival}:PreQueuedOperations"
  processingListName: "{Arrival}:ProcessingOperations"
  processingPrefix: "Processing"
  processingTimeoutMillis: 20000
  queuedOperationsListName: "{Execution}:QueuedOperations"
  dispatchingPrefix: "Dispatching"
  dispatchingTimeoutMillis: 10000
  dispatchedOperationsHashName: "DispatchedOperations"
  operationChannelPrefix: "OperationChannel"
  casPrefix: "ContentAddressableStorage"
  casExpire: 604800 # 1 week
  subscribeToBackplane: true
  runFailsafeOperation: true
  maxQueueDepth: 100000
  maxPreQueueDepth: 1000000
  redisQueueType: NORMAL
  timeout: 10000
  maxAttempts: 20
  cacheCas: false
  queues:
    - name: "cpu"
      allowUnmatched: true
      properties:
        - name: "min-cores"
          value: "*"
        - name: "max-cores"
          value: "*"
    - name: "gpu"
      allowUnmatched: true
      properties:
        - name: "gpu"
          value: "1"
worker:
  port: 8981
  publicName: "localhost:8981"
  capabilities:
    cas: true
    execution: true
  root: "/tmp/worker"
  inlineContentLimit: 1048567 # 1024 * 1024
  operationPollPeriod: 1
  dequeueMatchSettings:
    platform:
    acceptEverything: true
  cas:
    path: "cache"
    maxSizeBytes: 2147483648 # 2 * 1024 * 1024 * 1024
    maxEntrySizeBytes: 2147483648 # 2 * 1024 * 1024 * 1024
    fileDirectoriesIndexInMemory: false
    skipLoad: false
  executeStageWidth: 1
  inputFetchStageWidth: 1
  inputFetchDeadline: 60
  linkInputDirectories: true
  realInputDirectories: "external"
  defaultActionTimeout: 600
  maximumActionTimeout: 3600
  execOwner: