digestFunction: SHA256
defaultActionTimeout: 600
maximumActionTimeout: 3600
maxEntrySizeBytes: 2147483648 # 2 * 1024 * 1024 * 1024
prometheusPort: 9090
server:
  instanceType: SHARD
  name: shard
  actionCacheReadOnly: false
  port: 8980
  grpcMetrics:
    enabled: false
    provideLatencyHistograms: false
  maxInboundMessageSizeBytes: 0
  maxInboundMetadataSize: 0
  casWriteTimeout: 3600
  bytestreamTimeout: 3600
  sslCertificatePath:
  sslPrivateKeyPath:
  runDispatchedMonitor: true
  dispatchedMonitorIntervalSeconds: 1
  runOperationQueuer: true
  ensureOutputsPresent: false
  maxCpu: 0
  maxRequeueAttempts: 5
  useDenyList: true
  grpcTimeout: 3600
  executeKeepaliveAfterSeconds: 60
  recordBesEvents: false
  clusterId: local
  cloudRegion: us-east-1
  caches:
    directoryCacheMaxEntries: 10000
    commandCacheMaxEntries: 10000
    digestToActionCacheMaxEntries: 10000
    recentServedExecutionsCacheMaxEntries: 10000
  admin:
    deploymentEnvironment: AWS
    clusterEndpoint: "grpc://localhost"
    enableGracefulShutdown: false
  metrics:
    publisher: LOG
    logLevel: FINEST
    topic: test
    topicMaxConnections: 1000
    secretName: test
backplane:
  type: SHARD
  redisUri: "redis://localhost:6379"
  redisPassword:
  redisNodes:
  jedisPoolMaxTotal: 4000
  workersHashName: "Workers"
  workerChannel: "WorkerChannel"
  actionCachePrefix: "ActionCache"
  actionCacheExpire: 2419200 # 4 weeks
  actionBlacklistPrefix: "ActionBlacklist"
  actionBlacklistExpire: 3600 # 1 hour
  invocationBlacklistPrefix: "InvocationBlacklist"
  operationPrefix: "Operation"
  operationExpire: 604800 # 1 week
  casPrefix: "ContentAddressableStorage"
  casExpire: 604800 # 1 week
  subscribeToBackplane: true
  runFailsafeOperation: true
  cacheCas: false
worker:
  port: 8981
  grpcMetrics:
    enabled: false
    provideLatencyHistograms: false
  capabilities:
    cas: true
    execution: false
  root: "/tmp/worker"
  inlineContentLimit: 1048567 # 1024 * 1024 *
  storages:
    - type: FILESYSTEM
      path: "cache"
      maxSizeBytes: 2147483648 # 2 * 1024 * 1024 * 1024
      fileDirectoriesIndexInMemory: false
      skipLoad: false
      hexBucketLevels: 0
      execRootCopyFallback: false
      target:
      publishTtlMetric: false
