backplane:
  redisUri: redis://localhost:6379
  queues:
  - name: cpu
    properties:
    - name: '*'
      value: '*'
worker:
  publicName: localhost:8981
  dequeueMatchSettings:
    allowUnmatched: true
