server:
  digestFunction: SHA256
  instanceType: MEMORY
  name: memory
  list_operations_default_page_size: 1024
  list_operations_max_page_size: 16384
  tree_default_page_size: 1024
  tree_max_page_size: 16384
  operation_poll_timeout: 30
  operation_completed_delay: 10
  cas_config:
    memory:
      max_size_bytes: 1073741824 # 1024 * 1024 * 1024
  action_cache_config:
    delegate_cas:
  default_action_timeout: 600
  maximum_action_timeout: 3600
worker:
  digest_function: SHA256
  operation_queue:
    target: "localhost:8980"
    instance_name: "memory"
    deadline_after_seconds: 60
  content_addressable_storage:
    target: "localhost:8980"
    instance_name: "memory"
    deadline_after_seconds: 60
  action_cache:
    target: "localhost:8980"
    instance_name: "memory"
    deadline_after_seconds: 60
  root: "/tmp/worker"
  cas_cache_directory: "cache"
  cas_cache_max_size_bytes: 2147483648 # 2 * 1024 * 1024 * 1024
  cas_cache_max_entry_size_bytes: 2147483648 # 2 * 1024 * 1024 * 1024
  cas_cache_hex_bucket_levels: 0
  inline_content_limit: 1048567 # 1024 * 1024
  stream_stdout: true
  stdout_cas_policy: ALWAYS_INSERT
  stream_stderr: true
  stderr_cas_policy: ALWAYS_INSERT
  file_cas_policy: ALWAYS_INSERT
  tree_page_size: 0
  operation_poll_period: 1
  platform:
    properties:
      name: "key_name"
      value: "value_string"
  default_platform:
    properties:
      name: "cores"
      value: "1"
  execute_stage_width: 1
  input_fetch_stage_width: 1
  input_fetch_deadline: 60
  link_input_directories: true
  default_action_timeout: 600
  maximum_action_timeout: 3600
  exec_owner: ""
