name: Build and Push Latest Buildfarm Images

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    if: github.repository == 'buildfarm/buildfarm'
    name: Build Buildfarm Images
    runs-on: ubuntu-latest
    steps:
      - uses: bazelbuild/setup-bazelisk@v3

      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Bazelbuild Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.BAZELBUILD_DOCKERHUB_USERNAME }}
          password: ${{ secrets.BAZELBUILD_DOCKERHUB_TOKEN }}

      - name: Build Server Image
        id: buildAndPushServerImage
        run: bazel run //container:public_push_buildfarm-server -- --tag latest

      - name: Build Worker Image
        id: buildAndPushWorkerImage
        run: bazel run //container:public_push_buildfarm-worker -- --tag latest
