name: Build and Push Buildfarm Releases

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  build:
    if: github.repository == 'buildfarm/buildfarm'
    name: Build Buildfarm Images
    runs-on: ubuntu-latest
    steps:
      - uses: bazelbuild/setup-bazelisk@v2

      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Bazelbuild Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.BAZELBUILD_DOCKERHUB_USERNAME }}
          password: ${{ secrets.BAZELBUILD_DOCKERHUB_TOKEN }}

      - name: Build Server Image
        id: buildAndPushServerImage
        run: bazel run public_push_buildfarm-server-amd64 -- --tag ${{ github.event.release.tag_name }}

      - name: Build Worker Image
        id: buildAndPushWorkerImage
        run: bazel run public_push_buildfarm-worker-amd64 -- --tag ${{ github.event.release.tag_name }}

      - name: Build Server Image
        id: buildAndPushServerImage
        run: |
          bazel run public_push_buildfarm-server-arm64v8 -- \
            --tag ${{ github.event.release.tag_name }} \
            --platforms=@hermetic_cc_toolchain//toolchain/platform:linux_arm64 \
            --extra_toolchains @hermetic_cc_toolchain//toolchain/toolchain:linux_arm64_gnu.2.38

      - name: Build Worker Image
        id: buildAndPushWorkerImage
        run: |
          bazel run public_push_buildfarm-worker-arm64v8 -- \
            --tag ${{ github.event.release.tag_name }} \
            --platforms=@hermetic_cc_toolchain//toolchain/platform:linux_arm64 \
            --extra_toolchains @hermetic_cc_toolchain//toolchain/toolchain:linux_arm64_gnu.2.38
