---
name: Package and Publish Helm Chart

on:
  push:
    tags:
      - 'helm/*'

env:
  GH_TOKEN: ${{ github.token }}
  CHART_ROOT: kubernetes/helm-charts/buildfarm

jobs:
  lint:
    name: Lint Helm Chart
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: helm package
        run: |-
          set -ex
          helm dep up "${CHART_ROOT}"
          helm lint "${CHART_ROOT}"
  build:
    name: Package and Release BuildFarm Helm Chart
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: helm package
        run: |-
          set -ex
          helm dep up "${CHART_ROOT}"
          helm package "${CHART_ROOT}"
          gh release create "${{ github.ref_name }}" *.tgz
